### ISSUE TITLE
USER STORY: Ordering

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#10]
As a customer I can add menu items to an order so that I can choose multiple items before going to the checkout

## Tasks

- [x] Add add to order button on menu items 
- [x] Update order 
- [x] Add buttons to choose pickup or delivery
- [x] If delivery  ask for customer's address
- [x] Allow updating the number of each item 
- [x] Add button to place order 
- [x] Send order to database
