### ISSUE TITLE
USER STORY: Booking

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#11]
As a customer I can book a table online or by phone so that I know that there is a table available

## Tasks

- [x] Make a from and ask for first name, last name, number of guests, phone, date, time, and what restaurant
- [x] If the customer is logged in prepopulate customer details 
- [x] Display ability to call the restaurant to book a table; Choose a restaurant from dropdown, then display phone, address and open times
