### ISSUE TITLE
USER STORY: Guest User

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#13]
As a guest customer I can order without registering with the site

## Tasks

- [x] Allow non-registration table booking
- [ ] Allow non-registration food orders
- [ ] Add Cookies to save order items for non finished orders
