### ISSUE TITLE
USER STORY: Contact page

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#14]

**Comment by RobinGJonsson** [comment]
## Tasks

- [ ] Make contact.html 
- [ ] Ask to log in if the customer has an account 
- [ ] Add from and ask for the subject, first name, last name, email, and message 
- [ ] If the customer is logged in ask only for the subject and message
- [ ] Add send button
- [ ] Send it to the database
