### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#15]

**Comment by RobinGJonsson** [comment]
## Tasks

- [ ] Create db for customer
- [ ] Create db for restaurant
- [ ] Create db for booking
- [ ] Create db for order
