### ISSUE TITLE
USER STORY: Social media

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#16]
As a customer I can easily find the company's social media links so that can read more about them and share them with friends

## Tasks

- [x] Make footer in base.html
- [x] Import social media Icons
- [x] Link icons to corresponding sites
- [x] Style icons to change color to the company's main color when hovering
- [x] Write a copyright in the footer
