### ISSUE TITLE
USER STORY: Display Menu

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#17]
As a customer I can see the menu items so that I can choose what to order

## Tasks

- [x] Divide the menu page into three rows
- [x] Display 3 menu categories (menu, vegan, kids) with at least 3 menu items each
- [x] Place menu items into the relevant row 
- [x] Download relevant food pictures 
- [x] Add picture and food description
- [x] Add button to add the item to order
- [x] Link add button to orders
