### ISSUE TITLE
USER STORY: Navbar

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#3]
As a customer I can see different page options so that navigate the website pages

**Comment by RobinGJonsson** [comment]
## Tasks

- [x] Make a header in base.html
- [x] Add logo to header  
- [x] Add all page names with links to them 
- [x] Add the language change button and order button with relevant links in the top right-hand corner
- [x] Add profile link in the top right-hand corner if the customer is logged in, else show login/signup
