### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#4]
## Tasks

- [x] Create db for customer
- [x] Create db for restaurant
- [x] Create db for booking
- [x] Create db for order
- [x] Create db for menu items
- [x] Create db for order items
