### ISSUE TITLE
USER STORY: Contact page

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#5]
As a customer I can contact the company so that I can get help with complaints or need other help

**Comment by RobinGJonsson** [comment]
## Tasks

- [x] Make contact.html 
- [x] Add from and ask for the subject,  email, and message 
- [x] If the customer is logged in prepopulate the email field
- [x] Add send button
- [x] Send it to the database
