### ISSUE TITLE
USER STORY: Booking

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#7]
As a **customer** I can **book a table by phone or from the site** so that **I know that there is a table available**

**Comment by RobinGJonsson** [comment]
## Tasks

- [ ] Make a from and ask for first name, last name, number of guests, phone, date, time, and what restaurant
- [ ] If the customer is logged in don't ask for first name, last name or phone
- [ ] Display ability to call the restaurant to book a table; Choose a restaurant from dropdown, then display phone, address and open times
