### ISSUE TITLE
USER STORY: Ordering

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#9]
As a **customer** I can **add menu items to an order** so that **I can choose multiple items before going to the checkout**

**Comment by RobinGJonsson** [comment]
## Tasks

- [ ] Add add to order button on menu items 
- [ ] Update order 
- [ ] Link order button to the checkout page
- [ ] If customer  is not logged in ask to log in or allow to enter first name, last name, phone, email and restaurant 
- [ ] If customer is logged in ask to enter a restaurant
- [ ] Add buttons to choose pickup or delivery
- [ ] If delivery  ask for customer address
- [ ] Allow updating the number of each item 
- [ ] Add payment methods 
- [ ] Add button to place order
