### ISSUE TITLE
USER STORY: Notifications

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#9]
As a site user I can see a message or pop-up when I have changed something on the site so that I can know that my clicks have been received by the website

## Tasks 

- [x] Add message upon login 
- [x] Add message upon signup 
- [x] Add message upon deleted and updated booking
- [x] Add message upon updated customer details 
- [x] Add message upon item added to order 
- [x] Add message upon order made
